# Generated by Django 5.0.7 on 2026-04-22 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_username', models.CharField(max_length=255, unique=True)),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leader',
                'verbose_name_plural': 'Leaders',
                'db_table': 'leaders',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('chat_title', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('pt-br', 'Portuguese (Brazil)'), ('fr', 'French'), ('en', 'English'), ('es', 'Spanish'), ('ar', 'Arabic')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='bot_api.leader')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
                'unique_together': {('leader', 'language')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True)),
                ('nxtstar_uid', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('language', models.CharField(choices=[('pt-br', 'Portuguese (Brazil)'), ('fr', 'French'), ('en', 'English'), ('es', 'Spanish'), ('ar', 'Arabic')], default='en', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='bot_api.group')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invite_link', models.CharField(max_length=500, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='bot_api.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='bot_api.user')),
            ],
            options={
                'verbose_name': 'Invite Link',
                'verbose_name_plural': 'Invite Links',
                'db_table': 'invite_links',
                'indexes': [models.Index(fields=['user', 'status'], name='invite_link_user_id_a212c8_idx'), models.Index(fields=['group', 'status'], name='invite_link_group_i_e5d3b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('start', 'Start'), ('language_selected', 'Language Selected'), ('uid_check', 'UID Check'), ('user_verified', 'User Verified'), ('invite_created', 'Invite Created'), ('invite_used', 'Invite Used'), ('invite_declined', 'Invite Declined'), ('join_approved', 'Join Approved'), ('join_declined', 'Join Declined'), ('user_banned', 'User Banned')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='bot_api.user')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_log_user_id_3b54b4_idx'), models.Index(fields=['event_type', 'created_at'], name='audit_log_event_t_e775dd_idx')],
            },
        ),
    ]
