# Generated by Django 5.0.7 on 2026-04-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='chat_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
