# Generated by Django 5.0.7 on 2026-04-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0002_group_chat_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined_group',
        ),
        migrations.AddField(
            model_name='user',
            name='joined_groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='bot_api.group'),
        ),
    ]
