# Generated by Django 5.0.7 on 2026-05-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0004_alter_auditlog_event_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='group',
            name='leader',
        ),
    ]
