# Generated by Django 5.0.7 on 2026-05-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0005_alter_group_unique_together_remove_group_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('start', 'Start'), ('language_selected', 'Language Selected'), ('uid_check', 'UID Check'), ('user_verified', 'User Verified'), ('invite_created', 'Invite Created'), ('invite_used', 'Invite Used'), ('invite_declined', 'Invite Declined'), ('join_approved', 'Join Approved'), ('join_declined', 'Join Declined'), ('user_banned', 'User Banned'), ('group_left', 'Group Left')], max_length=50),
        ),
    ]
